package thaumcraft;


import thaumcraft.client.gui.TCKnowledgeGainHud;
import thaumcraft.client.gui.TCResearchIconRenderer;
import com.mojang.logging.LogUtils;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.fml.loading.FMLEnvironment;
import net.neoforged.neoforge.common.NeoForge;
import org.slf4j.Logger;
import thaumcraft.client.TCItemProperties;
import thaumcraft.client.TCClientExtensions;
import thaumcraft.client.gui.TCClientTooltipComponents;
import thaumcraft.client.gui.TCMenuScreens;
import thaumcraft.client.renderer.TCBlockEntityRenderers;
import thaumcraft.client.renderer.TCEntityRenderers;
import thaumcraft.common.aspects.TCAspectAssignments;
import thaumcraft.common.aspects.TCAspectDumpExporter;
import thaumcraft.common.aspects.TCAspectReloadValidator;
import thaumcraft.common.blocks.world.taint.TCFluxTaintBlockerAuditExporter;
import thaumcraft.common.blocks.world.taint.TCTaintEcologyBlockerAuditExporter;
import thaumcraft.common.crafting.infusion.TCInfusionBehaviorAuditExporter;
import thaumcraft.common.crafting.infusion.TCInfusionNetwork;
import thaumcraft.common.aspects.TCGeneratedAspectRecipeGenerator;
import thaumcraft.common.crafting.crucible.TCCrucibleBehaviorAuditExporter;
import thaumcraft.common.crafting.crucible.TCSpecialAlchemyBehaviorAuditExporter;
import thaumcraft.common.crafting.crucible.TCThaumatoriumBehaviorAuditExporter;
import thaumcraft.common.crafting.crucible.TCThaumatoriumNetwork;
import thaumcraft.common.entities.TCEntityFoundationAuditExporter;
import thaumcraft.common.entities.TCEntityFXNetwork;
import thaumcraft.common.entities.TCEntitySpawnPolicyAuditExporter;
import thaumcraft.common.entities.TCEntitySpawnRules;
import thaumcraft.common.entities.TCFallingTaintBlockerAuditExporter;
import thaumcraft.common.entities.TCFluxBoreThaumatoriumBlockerAuditExporter;
import thaumcraft.common.entities.TCFluxRiftConsequenceAuditExporter;
import thaumcraft.common.entities.TCTaintMobBlockerAuditExporter;
import thaumcraft.common.entities.TCWispBehaviorAuditExporter;
import thaumcraft.common.essentia.transport.TCEssentiaTransportBehaviorAuditExporter;
import thaumcraft.common.tiles.devices.TCLampDeviceAuditExporter;
import thaumcraft.common.tiles.devices.TCInfernalFurnaceBehaviorAuditExporter;
import thaumcraft.common.tiles.devices.TCMirrorBehaviorAuditExporter;
import thaumcraft.common.tiles.devices.TCAlchemyAutomationDeviceAuditExporter;
import thaumcraft.common.tiles.devices.TCBrainJarBehaviorAuditExporter;
import thaumcraft.common.tiles.devices.TCStandaloneDeviceBlockerAuditExporter;
import thaumcraft.common.runtime.TCMinimalGameTestFixtureExporter;
import thaumcraft.common.essentia.transport.TCEssentiaCapabilities;
import thaumcraft.common.config.TCConfig;
import thaumcraft.common.capabilities.TCMachineCapabilities;
import thaumcraft.common.items.TCFuelEvents;
import thaumcraft.common.items.consumables.TCBathSaltsEvents;
import thaumcraft.common.items.consumables.TCLiquidDeathEvents;
import thaumcraft.common.crafting.arcane.TCArcaneWorkbenchAuditExporter;
import thaumcraft.common.items.casters.TCFocusCasterCoreAuditExporter;
import thaumcraft.common.items.casters.TCFocusCastExecutionAuditExporter;
import thaumcraft.common.items.casters.TCFocalManipulatorNetwork;
import thaumcraft.common.items.equipment.TCItemEquipmentBehaviorAuditExporter;
import thaumcraft.common.registry.TCBlockEntities;
import thaumcraft.common.registry.TCBlocks;
import thaumcraft.common.registry.TCArmorMaterials;
import thaumcraft.common.registry.TCCreativeTabs;
import thaumcraft.common.registry.TCDataComponents;
import thaumcraft.common.registry.TCEntityTypes;
import thaumcraft.common.registry.TCFluids;
import thaumcraft.common.registry.TCFeatures;
import thaumcraft.common.registry.TCItems;
import thaumcraft.common.registry.TCMenus;
import thaumcraft.common.registry.TCMobEffects;
import thaumcraft.common.registry.TCRecipes;
import thaumcraft.common.registry.TCSounds;
import thaumcraft.common.research.TCKnowledgeCommands;
import thaumcraft.common.research.TCKnowledgeNetwork;
import thaumcraft.common.research.TCArcaneRecipeAuditExporter;
import thaumcraft.common.research.TCResearchDiscoveryEvents;
import thaumcraft.common.research.TCResearchManager;
import thaumcraft.common.research.TCResearchDataAuditExporter;
import thaumcraft.common.research.TCResearchPageCatalogManager;
import thaumcraft.common.research.TCResearchPageCatalogAuditExporter;
import thaumcraft.common.research.TCResearchPageCatalogCommands;
import thaumcraft.common.research.TCThaumonomiconNetwork;
import thaumcraft.common.research.TCThaumonomiconProtocolAuditExporter;
import thaumcraft.common.research.TCResearchRequirementAuditCommands;
import thaumcraft.common.research.TCResearchRequirementAuditExporter;
import thaumcraft.common.research.TCScanningCommands;
import thaumcraft.common.research.TCScanningManager;
import thaumcraft.common.research.theorycraft.TCResearchTableAuditCommands;
import thaumcraft.common.research.theorycraft.TCResearchTableAuditExporter;
import thaumcraft.common.research.theorycraft.TCResearchTableNetwork;
import thaumcraft.common.research.theorycraft.TCTheorycraftManager;
import thaumcraft.common.warp.TCWarpCommands;
import thaumcraft.common.warp.TCWarpBehaviorAuditExporter;
import thaumcraft.common.warp.TCWarpCraftingEvents;
import thaumcraft.common.warp.TCWarpEventBehaviorAuditExporter;
import thaumcraft.common.warp.TCWarpEvents;
import thaumcraft.common.warp.TCWarpItemRegistry;
import thaumcraft.common.warp.TCWarpNetwork;
import thaumcraft.common.world.aura.TCAuraDebugCommands;
import thaumcraft.common.world.aura.TCAuraEvents;
import thaumcraft.common.world.aura.TCAuraNetwork;

@Mod(Thaumcraft.MODID)
public final class Thaumcraft {
    public static final String MODID = "thaumcraft";
    public static final Logger LOGGER = LogUtils.getLogger();

    public Thaumcraft(IEventBus modEventBus, ModContainer modContainer) {
        TCDataComponents.DATA_COMPONENT_TYPES.register(modEventBus);
        TCFluids.FLUID_TYPES.register(modEventBus);
        TCFluids.FLUIDS.register(modEventBus);
        TCBlocks.BLOCKS.register(modEventBus);
        TCFeatures.FEATURES.register(modEventBus);
        TCBlockEntities.BLOCK_ENTITY_TYPES.register(modEventBus);
        TCMobEffects.MOB_EFFECTS.register(modEventBus);
        TCEntityTypes.ENTITY_TYPES.register(modEventBus);
        TCArmorMaterials.ARMOR_MATERIALS.register(modEventBus);
        TCItems.ITEMS.register(modEventBus);
        TCMenus.MENUS.register(modEventBus);
        TCRecipes.RECIPE_TYPES.register(modEventBus);
        TCRecipes.RECIPE_SERIALIZERS.register(modEventBus);
        TCSounds.SOUND_EVENTS.register(modEventBus);
        TCCreativeTabs.CREATIVE_MODE_TABS.register(modEventBus);
        modEventBus.addListener(TCEntityTypes::onEntityAttributeCreation);
        modEventBus.addListener(TCEntitySpawnRules::onRegisterSpawnPlacements);
        if (FMLEnvironment.dist == Dist.CLIENT) {
            TCClientTooltipComponents.register(modEventBus);
            TCMenuScreens.register(modEventBus);
            TCBlockEntityRenderers.register(modEventBus);
            TCEntityRenderers.register(modEventBus);
            TCKnowledgeGainHud.register(modEventBus);
            TCItemProperties.register(modEventBus);
            TCClientExtensions.register(modEventBus);
            TCResearchIconRenderer.register(modEventBus);
        }
        modEventBus.addListener(TCAuraNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCInfusionNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCThaumatoriumNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCKnowledgeNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCWarpNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCResearchTableNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCThaumonomiconNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCFocalManipulatorNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCEntityFXNetwork::onRegisterPayloadHandlers);
        modEventBus.addListener(TCEssentiaCapabilities::register);
        modEventBus.addListener(TCMachineCapabilities::register);
        modContainer.registerConfig(ModConfig.Type.COMMON, TCConfig.SPEC);
        NeoForge.EVENT_BUS.addListener(TCAspectAssignments::onAddReloadListeners);
        NeoForge.EVENT_BUS.addListener(TCFuelEvents::onFuelBurnTime);
        NeoForge.EVENT_BUS.addListener(TCLiquidDeathEvents::onLivingDrops);
        NeoForge.EVENT_BUS.addListener(TCResearchManager::onAddReloadListeners);
        NeoForge.EVENT_BUS.addListener(TCResearchPageCatalogManager::onAddReloadListeners);
        NeoForge.EVENT_BUS.addListener(TCScanningManager::onAddReloadListeners);
        NeoForge.EVENT_BUS.addListener(TCGeneratedAspectRecipeGenerator::onTagsUpdated);
        NeoForge.EVENT_BUS.addListener(TCAspectReloadValidator::onTagsUpdated);
        NeoForge.EVENT_BUS.addListener(TCAspectDumpExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCAuraEvents::onServerTick);
        NeoForge.EVENT_BUS.addListener(TCAuraEvents::onChunkLoad);
        NeoForge.EVENT_BUS.addListener(TCAuraEvents::onChunkUnload);
        NeoForge.EVENT_BUS.addListener(TCAuraDebugCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(TCKnowledgeCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(TCKnowledgeNetwork::onPlayerLoggedIn);
        NeoForge.EVENT_BUS.addListener(TCKnowledgeNetwork::onPlayerRespawn);
        NeoForge.EVENT_BUS.addListener(TCKnowledgeNetwork::onPlayerChangedDimension);
        NeoForge.EVENT_BUS.addListener(TCWarpNetwork::onPlayerLoggedIn);
        NeoForge.EVENT_BUS.addListener(TCWarpNetwork::onPlayerRespawn);
        NeoForge.EVENT_BUS.addListener(TCWarpNetwork::onPlayerChangedDimension);
        NeoForge.EVENT_BUS.addListener(TCWarpEvents::onServerTick);
        NeoForge.EVENT_BUS.addListener(TCWarpEvents::onFinishUsingItem);
        NeoForge.EVENT_BUS.addListener(TCResearchRequirementAuditCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(TCResearchRequirementAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCResearchDataAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCResearchPageCatalogAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCThaumonomiconProtocolAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCArcaneRecipeAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCArcaneWorkbenchAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCCrucibleBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCSpecialAlchemyBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCThaumatoriumBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCInfusionBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCEssentiaTransportBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCMirrorBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCLampDeviceAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCInfernalFurnaceBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCAlchemyAutomationDeviceAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCBrainJarBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCStandaloneDeviceBlockerAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCEntityFoundationAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCEntitySpawnPolicyAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCFluxBoreThaumatoriumBlockerAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCFluxRiftConsequenceAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCWispBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCFluxTaintBlockerAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCTaintEcologyBlockerAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCTaintMobBlockerAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCFallingTaintBlockerAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCItemEquipmentBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCFocusCasterCoreAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCFocusCastExecutionAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCWarpBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCWarpEventBehaviorAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCMinimalGameTestFixtureExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCResearchPageCatalogCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(TCResearchTableAuditCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(TCResearchTableAuditExporter::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCScanningCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(TCWarpCommands::onRegisterCommands);
        NeoForge.EVENT_BUS.addListener(TCScanningManager::onServerStarted);
        NeoForge.EVENT_BUS.addListener(TCWarpCraftingEvents::onItemCrafted);
        NeoForge.EVENT_BUS.addListener(TCResearchManager::onItemCrafted);
        NeoForge.EVENT_BUS.addListener(TCResearchDiscoveryEvents::onItemPickup);
        NeoForge.EVENT_BUS.addListener(TCResearchDiscoveryEvents::onPlayerWakeUp);
        NeoForge.EVENT_BUS.addListener(TCBathSaltsEvents::onItemExpire);
        TCAspectAssignments.bootstrap();
        TCResearchManager.bootstrap();
        TCResearchPageCatalogManager.bootstrap();
        TCTheorycraftManager.bootstrap();
        TCScanningManager.bootstrap();
        TCWarpItemRegistry.bootstrap();

        LOGGER.info("Thaumcraft NeoForge bootstrap initialized.");
    }
}
